In [2]:
import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt
from pandas_datareader import data as web

In [9]:
v=[1,2,3,4,5]

In [10]:
v

[1, 2, 3, 4, 5]

In [11]:
a=np.arange(15).reshape(5,3)

In [12]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [13]:
a.mean(axis=0)

array([ 6.,  7.,  8.])

In [14]:
a.mean(axis=1)

array([  1.,   4.,   7.,  10.,  13.])

In [15]:
a.std()

4.3204937989385739

In [23]:
column_name=list('abc')

In [24]:
column_name

['a', 'b', 'c']

In [26]:
index_name=pd.date_range('2017-7-1',periods=5,freq='B')

In [27]:
index_name

DatetimeIndex(['2017-07-03', '2017-07-04', '2017-07-05', '2017-07-06',
               '2017-07-07'],
              dtype='datetime64[ns]', freq='B')

In [28]:
df=pd.DataFrame(a,columns=column_name,index=index_name)

In [29]:
df

a   b   c
2017-07-03   0   1   2
2017-07-04   3   4   5
2017-07-05   6   7   8
2017-07-06   9  10  11
2017-07-07  12  13  14

In [30]:
b=np.arange(15).reshape(5,3)


In [31]:
df1=pd.DataFrame(b,columns=list('abc'), index=pd.date_range('2017-1-1',periods=5,freq='D'))

In [32]:
df1

a   b   c
2017-01-01   0   1   2
2017-01-02   3   4   5
2017-01-03   6   7   8
2017-01-04   9  10  11
2017-01-05  12  13  14

In [4]:
data = web.DataReader('GOOG','google','2016-10-31')

ProxyError: HTTPConnectionPool(host='lobluecoatp7.nomura.com', port=80): Max retries exceeded with url: http://www.google.com/finance/historical?q=GOOG&startdate=Oct+31%2C+2016&enddate=Jul+25%2C+2017&output=csv (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000000A91A3C8>: Failed to establish a new connection: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))

In [3]:
data=pd.read_csv('C:/Users/karagiag/Downloads/aapl.csv', index_col=0, parse_dates=True)

In [4]:
data.rename(columns={'Close':'price'},inplace=True)

In [5]:
data = data.sort_index()

In [6]:
data

Open    High     Low   price     Volume
Date                                                
2011-01-03   46.52   47.18   46.41   47.08  111280407
2011-01-04   47.49   47.50   46.88   47.33   77337001
2011-01-05   47.08   47.76   47.07   47.71   63879193
2011-01-06   47.82   47.89   47.56   47.68   75106626
2011-01-07   47.71   48.05   47.41   48.02   77982212
2011-01-10   48.40   49.03   48.17   48.92  112139482
2011-01-11   49.27   49.28   48.50   48.81  111019993
2011-01-12   49.04   49.20   48.86   49.20   75644310
2011-01-13   49.31   49.52   49.12   49.38   74536182
2011-01-14   49.41   49.78   49.21   49.78   77209748
2011-01-18   47.07   49.25   46.57   48.66  470246700
2011-01-19   49.76   49.80   48.13   48.41  283902199
2011-01-20   48.06   48.33   47.16   47.53  191197293
2011-01-21   47.68   47.84   46.66   46.67  188599712
2011-01-24   46.70   48.21   46.67   48.21  143670548
2011-01-25   48.05   48.78   47.80   48.77  136716650
2011-01-26   48.99   49.37   48.79   49.12  126716779
2011-01-27   49.11   49.24   48.98   49.03   71255961
2011-01-28   49.17   49.20   47.65   48.01  148014146
2011-01-31   47.97   48.58   47.76   48.47   94311602
2011-02-01   48.76   49.38   48.71   49.29  106657943
2011-02-02   49.21   49.32   49.08   49.19   64738807
2011-02-03   49.11   49.18   48.36   49.06   98449148
2011-02-04   49.09   49.53   49.07   49.50   80459575
2011-02-07   49.70   50.46   49.66   50.27  121254910
2011-02-08   50.53   50.79   50.31   50.74   95259906
2011-02-09   50.74   51.29   50.70   51.17  120686090
2011-02-10   51.06   51.43   49.71   50.65  232137360
2011-02-11   50.68   51.11   50.51   50.98   91892948
2011-02-14   50.97   51.35   50.96   51.31   77603491
...            ...     ...     ...     ...        ...
2016-11-17  109.81  110.35  108.83  109.95   26964598
2016-11-18  109.72  110.54  109.66  110.06   28428917
2016-11-21  110.12  111.99  110.01  111.73   29264571
2016-11-22  111.95  112.42  111.40  111.80   25965534
2016-11-23  111.36  111.51  110.33  111.23   27426394
2016-11-25  111.47  111.87  110.95  111.79   11475922
2016-11-28  111.43  112.46  111.39  111.57   27193983
2016-11-29  110.78  112.03  110.07  111.46   28528750
2016-11-30  111.60  112.20  110.27  110.52   36162258
2016-12-01  110.36  110.94  109.03  109.49   37086862
2016-12-02  109.17  110.09  108.85  109.90   26527997
2016-12-05  110.00  110.03  108.25  109.11   34324540
2016-12-06  109.50  110.36  109.19  109.95   26195462
2016-12-07  109.26  111.19  109.16  111.03   29998719
2016-12-08  110.86  112.43  110.60  112.12   27068316
2016-12-09  112.31  114.70  112.31  113.95   34402627
2016-12-12  113.29  115.00  112.49  113.30   26374377
2016-12-13  113.84  115.92  113.75  115.19   43733811
2016-12-14  115.04  116.20  114.98  115.19   34031834
2016-12-15  115.38  116.73  115.23  115.82   46524544
2016-12-16  116.47  116.50  115.64  115.97   44351134
2016-12-19  115.80  117.38  115.75  116.64   27779423
2016-12-20  116.74  117.50  116.68  116.95   21424965
2016-12-21  116.80  117.40  116.78  117.06   23783165
2016-12-22  116.35  116.51  115.64  116.29   26085854
2016-12-23  115.59  116.52  115.59  116.52   14249484
2016-12-27  116.52  117.80  116.49  117.26   18296855
2016-12-28  117.52  118.02  116.20  116.76   20905892
2016-12-29  116.45  117.11  116.40  116.73   15039519
2016-12-30  116.65  117.20  115.43  115.82   30586265

[1510 rows x 5 columns]

In [7]:
data['SMA1'] = data['price'].rolling(42).mean()

In [8]:
data['SMA2'] = data['price'].rolling(230).mean()

In [ ]:
data[['price','SMA1','SMA2']].plot(title='AAPL stock price | 42 & 252 days SMAs',figsize=(10, 6))

In [ ]:
plt.show()

In [14]:
data['position'] = np.where(data['SMA1']>data['SMA2'],1,-1)

In [15]:
data.dropna(inplace=True)

In [12]:
data['position'].plot(ylim=[-1.1,1.1],title='Market Positioning')

In [13]:
plt.show()

In [16]:
data['returns']= np.log(data['price']/data['price'].shift(1))

In [15]:
data['returns'].hist(bins=50)

In [16]:
plt.show()

In [18]:
data['strategy'] = data['position'].shift(1) * data['returns']
data[['returns', 'strategy']].sum()

returns     0.775913
strategy    1.049341
dtype: float64

In [19]:
data[['returns', 'strategy']].cumsum().apply(np.exp).plot(figsize=(10, 6))

In [20]:
plt.show()

In [41]:
data[['returns', 'strategy']].mean() * 252

returns     0.150330
strategy    0.154484
dtype: float64

In [42]:
data[['returns', 'strategy']].std() * 252 ** 0.5

returns     0.261678
strategy    0.261668
dtype: float64

In [43]:
data['cumret'] = data['strategy'].cumsum().apply(np.exp)  

In [44]:
data['cummax'] = data['cumret'].cummax()

In [53]:
data[['cumret', 'cummax']].plot(figsize=(10, 6))  

In [54]:
plt.show()

In [47]:
data['drawdown'] = (data['cummax']-data['cumret'])

In [48]:
data['drawdown'].max()

0.83436175898276721

In [49]:
temp = data['drawdown'][data['drawdown'] == 0]  

In [50]:
periods = (temp.index[1:].to_pydatetime()-temp.index[:1].to_pydatetime())

In [51]:
periods.max()

datetime.timedelta(1511)