In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [87]:
import statsmodels.api as sm

In [88]:
x=np.arange(12)
print x

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [89]:
lags = 3

In [91]:
m= np.zeros((lags+1, len(x) - lags))

In [95]:
for i in range(lags+1):
    if i==lags:
        m[i] = x[i:]
    else:
        m[i] = x[i:i-lags]

In [97]:
m

array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.],
       [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
       [  2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [  3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.]])

In [100]:
m[0] # This is my 3rd lagged variable x(t-3). m[1] is my second lagged variable x(t-2) etc..

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [98]:
m[3] # This is my dependent variable y

array([  3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.])

In [101]:
m.T # transosing the matrix =>first 3 columns are the lagged x's and final column is y. 

array([[  0.,   1.,   2.,   3.],
       [  1.,   2.,   3.,   4.],
       [  2.,   3.,   4.,   5.],
       [  3.,   4.,   5.,   6.],
       [  4.,   5.,   6.,   7.],
       [  5.,   6.,   7.,   8.],
       [  6.,   7.,   8.,   9.],
       [  7.,   8.,   9.,  10.],
       [  8.,   9.,  10.,  11.]])

In [107]:
reg = np.linalg.lstsq(m[:lags].T, m[lags])[0] 
#Solves the equation `a x = b` by computing a vector `x` of the regression coefficients
# It will return an array of residuals as well hence we take the first output array [0]
print reg

[-0.66666667  0.33333333  1.33333333]


In [108]:
np.dot(m[:lags].T, reg)  #The dot product yields the prediction results.

array([  3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.])

In [ ]:
#S&P 500 index level predicted values based on linear regression (3 lags) 

In [3]:
data = pd.read_csv('C:/Users/karagiag/Downloads/^GSPC.csv', index_col=0, parse_dates=True)

In [4]:
data.rename(columns={'Adj Close':'price'}, inplace = True)

In [5]:
lags=3

In [6]:
m=np.zeros((lags+1,len(data)-lags))

In [7]:
for i in range(lags+1):
    if i==lags:
        m[i]=data.price[i:]
    else:
        m[i]= data.price[i:i - lags]

In [8]:
reg = np.linalg.lstsq(m[:lags].T, m[lags])[0]
print reg

[ 0.02241678 -0.00328817  0.98130225]


In [9]:
p=np.dot(m[:lags].T,reg)

In [10]:
data['prediction']=0.0

In [11]:
data['prediction'].iloc[lags:] = p  

C:\Program Files\Continuum Analytics\Anaconda2\lib\site-packages\pandas\core\indexing.py:128: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


In [12]:
data[['price', 'prediction']].ix[lags:].plot(figsize=(10, 6))  

In [13]:
plt.show()

In [167]:
data[['price','prediction']][data.index>'2017-7-1'].plot() # Zoom in a smaller data window

In [168]:
plt.show()

In [ ]:
#Predicting Future Returns

In [15]:
data['returns']=np.log(data['price']/data['price'].shift(1))

In [ ]:
m = np.zeros((lags+1, len(data))

In [16]:
for i in range(lags+1):
    if i==lags:
        m[i] = data.returns[i:]
    else:
        m[i] = data.returns[i:i - lags]

In [17]:
reg = np.linalg.lstsq(m[:lags].T,m[lags])[0]
print reg

[-0.00753196  0.01886129  0.00232656]


In [18]:
p = np.dot(m[:lags].T, reg)

In [19]:
data['prediction'] = 0.0

In [20]:
data['prediction'].iloc[lags:] = p

In [21]:
data[['returns', 'prediction']].ix[lags:].plot(figsize=(10, 6))

In [22]:
plt.show()

In [23]:
hits = np.sign(data['returns'].ix[lags:] * data['prediction'].ix[lags:]).value_counts()  

In [24]:
hits

 1.0    629
-1.0    623
 0.0      1
dtype: int64

In [27]:
ratio = hits.values[0] / sum(hits)  
print ratio

0
