In [2]:
import numpy as np

In [3]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [4]:
zeroArray = np.zeros((2,3))

In [5]:
print zeroArray

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [6]:
oneArray = np.ones((2,3))

In [8]:
print oneArray

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [9]:
randomArray = np.random.random((2,3))
print randomArray

[[ 0.6493192   0.66943489  0.82844848]
 [ 0.22340396  0.21956527  0.95987514]]


In [11]:
randomArray[1,1]

0.21956527020939232

In [12]:
rangeArray = np.arange(6,12)
rangeArray

array([ 6,  7,  8,  9, 10, 11])

In [13]:
rangeArray.reshape((2,3))

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
squareArray = np.arange(1,10)
print squareArray

[1 2 3 4 5 6 7 8 9]


In [19]:
squareArray = squareArray.reshape((3,3))

In [20]:
squareArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
squareArray[0,0:2]

array([1, 2])

In [22]:
squareArray[1:3,1:3]

array([[5]])

In [23]:
randomRow = np.random.random((10,1))

In [24]:
randomRow

array([[ 0.99216684],
       [ 0.80205099],
       [ 0.12468758],
       [ 0.82758194],
       [ 0.17145529],
       [ 0.37558369],
       [ 0.16512118],
       [ 0.17759981],
       [ 0.63219029],
       [ 0.98593392]])

In [25]:
fibIndices = np.array([1,1,2,3])

In [26]:
randomRow[fibIndices]

array([[ 0.80205099],
       [ 0.80205099],
       [ 0.12468758],
       [ 0.82758194]])