In [1]:
import numpy as np
import pandas as pd
import math

In [3]:
v=[1,2,3,4,5]

In [7]:
v

[1, 2, 3, 4, 5]

In [6]:
a

array([1, 2, 3, 4, 5])

In [25]:
a=np.arange(15).reshape(5,3)

In [23]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [19]:
a.mean(axis=0)

array([ 4.5,  5.5,  6.5])

In [21]:
a.mean(axis=1)

array([  1.,   4.,   7.,  10.])

In [13]:
a.std()

3.4520525295346629

In [26]:
columns=list('abc')

In [27]:
columns

['a', 'b', 'c']

In [48]:
index=pd.date_range('2017-7-1',periods=5,freq='B')

In [49]:
index

DatetimeIndex(['2017-07-03', '2017-07-04', '2017-07-05', '2017-07-06',
               '2017-07-07'],
              dtype='datetime64[ns]', freq='B')

In [50]:
df=pd.DataFrame(a,columns=columns,index=index)

In [51]:
df

a   b   c
2017-07-03   0   1   2
2017-07-04   3   4   5
2017-07-05   6   7   8
2017-07-06   9  10  11
2017-07-07  12  13  14

In [52]:
b=np.arange(15).reshape(5,3)


In [53]:
df1=pd.DataFrame(b,columns=list('abc'), index=pd.date_range('2017-1-1',periods=5,freq='D'))

In [54]:
df1

a   b   c
2017-01-01   0   1   2
2017-01-02   3   4   5
2017-01-03   6   7   8
2017-01-04   9  10  11
2017-01-05  12  13  14

In [56]:
from pandas_datareader import data as web

In [60]:
data = web.DataReader('AAPL','google','2016-10-31')

In [58]:
close = data{}

Open    High     Low   Close    Volume
Date                                                
2016-10-31  113.65  114.23  113.20  113.54  26419398
2016-11-01  113.46  113.77  110.53  111.49  43825812
2016-11-02  111.40  112.35  111.23  111.59  28331709
2016-11-03  110.98  111.46  109.55  109.83  26932602
2016-11-04  108.53  110.25  108.11  108.84  30836997
2016-11-07  110.08  110.51  109.46  110.41  32560000
2016-11-08  110.31  111.72  109.70  111.06  24254179
2016-11-09  109.88  111.32  108.05  110.88  59176361
2016-11-10  111.09  111.09  105.83  107.79  57134541
2016-11-11  107.12  108.87  106.55  108.43  34143898
2016-11-14  107.71  107.81  104.08  105.71  51175504
2016-11-15  106.57  107.68  106.16  107.11  32264510
2016-11-16  106.70  110.23  106.60  109.99  58840522
2016-11-17  109.81  110.35  108.83  109.95  26964598
2016-11-18  109.72  110.54  109.66  110.06  28428917
2016-11-21  110.12  111.99  110.01  111.73  29264571
2016-11-22  111.95  112.42  111.40  111.80  25965534
2016-11-23  111.36  111.51  110.33  111.23  27426394
2016-11-25  111.47  111.87  110.95  111.79  11475922
2016-11-28  111.43  112.46  111.39  111.57  27193983
2016-11-29  110.78  112.03  110.07  111.46  28528750
2016-11-30  111.60  112.20  110.27  110.52  36162258
2016-12-01  110.36  110.94  109.03  109.49  37086862
2016-12-02  109.17  110.09  108.85  109.90  26527997
2016-12-05  110.00  110.03  108.25  109.11  34324540
2016-12-06  109.50  110.36  109.19  109.95  26195462
2016-12-07  109.26  111.19  109.16  111.03  29998719
2016-12-08  110.86  112.43  110.60  112.12  27068316
2016-12-09  112.31  114.70  112.31  113.95  34402627
2016-12-12  113.29  115.00  112.49  113.30  26374377
...            ...     ...     ...     ...       ...
2017-05-04  146.52  147.14  145.81  146.53  23371872
2017-05-05  146.76  148.98  146.76  148.96  27327725
2017-05-08  149.03  153.70  149.03  153.01  48752413
2017-05-09  153.87  154.88  153.45  153.99  39130363
2017-05-10  153.63  153.94  152.11  153.26  25805692
2017-05-11  152.45  154.07  152.31  153.95  27255058
2017-05-12  154.70  156.42  154.67  156.10  32527017
2017-05-15  156.01  156.65  155.05  155.70  26009719
2017-05-16  155.94  156.06  154.72  155.47  20048478
2017-05-17  153.60  154.57  149.71  150.25  50767678
2017-05-18  151.27  153.34  151.13  152.54  33568215
2017-05-19  153.38  153.98  152.63  153.06  26960788
2017-05-22  154.00  154.58  152.91  153.99  22966437
2017-05-23  154.90  154.90  153.31  153.80  19918871
2017-05-24  153.84  154.17  152.67  153.34  19219154
2017-05-25  153.73  154.35  153.03  153.87  19235598
2017-05-26  154.00  154.24  153.31  153.61  21927637
2017-05-30  153.42  154.43  153.33  153.67  20126851
2017-05-31  153.97  154.17  152.38  152.76  24451164
2017-06-01  153.17  153.33  152.22  153.18  16404088
2017-06-02  153.58  155.45  152.89  155.45  27770715
2017-06-05  154.34  154.45  153.46  153.93  25331662
2017-06-06  153.90  155.81  153.78  154.45  26624926
2017-06-07  155.02  155.98  154.48  155.37  21069647
2017-06-08  155.25  155.54  154.40  154.99  21250798
2017-06-09  155.19  155.19  146.02  148.98  64882657
2017-06-12  145.74  146.09  142.51  145.42  72307330
2017-06-13  147.16  147.45  145.15  146.59  34165445
2017-06-14  147.50  147.50  143.84  145.16  31531232
2017-06-15  143.32  144.48  142.21  144.29  32165373

[157 rows x 5 columns]